//for game.js
const MIN_MONSTER_SPAWN_HEIGHT = 250;
const MONSTER_HEIGHT_DECREMENT_BY = 20;
const PICKUP_FREQUENCY = 5;
const MAX_MONSTER_WIDTH = 158;
const LOWEST_JUMP_HEIGHT = -10;
const MEDIUM_JUMP_HEIGHT = -15;
const JETPACK_JUMP_HEIGHT = -20;
const ROCKET_JUMP_HEIGHT = -30;
const SCORE_INCREMENT = 0.1;
const PICKUP_ACCELERATION = 0.10;



//monster
const MONSTER_MOVE_THRESHOLD = 20;
const AWKWARD_MOVER_FLIP_DURATION = 10;


//pickup
const PICKUP_SHIFT_X = 10;

//player
const ANGLE_MULTIPLE = 6;
const ADDITIONAL_TRANSLATION_X = 25;
const ADDITIONAL_TRANSLATION_Y = 25;
const JUMP_THRESHOLD = 300;
const TURE_ACCELERATION = 0.25;
const X_VELOCITY = 0.5;
const APPEAR_RIGHT_POSITION = 400;
const FRICTION = 0.9;
const ANIMATION_FRAME_THRESHOLD = 20;
const ROCKET_WIDTH =  72;
const ROCKET_HEIGHT = 129;
const SPRING_JUMP_COUNT = 5;
const SHIELD_COUNT = 3;